### ISSUE TITLE
Version 3.3.0

### ISSUE THREAD

**Issue by JRSKelvin** [rapdodge/GenshinRepository#1]
For version 3.3.0 has been released, can you help add the version 3.3.0 readme file?
Untuk versi 3.3.0 sudah rilis, apakah bisa bantu tambahkan file readme untuk versi 3.3.0?

**Comment by rapdodge** [comment]
Dear @JRSKelvin,
Already done https://github.com/rapdodge/GenshinRepository/commit/d8db6855169094644e493968ab35143db8e1810a

**Comment by JRSKelvin** [comment]
Dear @rapdodge,
Thank you for your fast response and update.

**Comment by rapdodge** [comment]
You're welcome
